package com.example.lttle_lemon_app.ui.theme

import androidx.compose.ui.graphics.Color

object LLColor {
    val green = Color(0xFF495E57)
    val yellow = Color(0xFFF4CE14)

    val pink = Color(0xFFFBDABB)
    val peach = Color(0xFFFBDABB)

    val cloud = Color(0xFFEDEFEE)
    val charcoal = Color(0xFF333333)
}

val md_theme_light_primary = Color(0xFF495E57)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7CF8D8)
val md_theme_light_onPrimaryContainer = Color(0xFF002019)
val md_theme_light_secondary = Color(0xFF99461B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCC)
val md_theme_light_onSecondaryContainer = Color(0xFF351000)
val md_theme_light_tertiary = Color(0xFF895200)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCBC)
val md_theme_light_onTertiaryContainer = Color(0xFF2C1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFEDEFEE)
val md_theme_light_onBackground = Color(0xFF002022)
val md_theme_light_surface = Color(0xFFEDEFEE)
val md_theme_light_onSurface = Color(0xFF002022)
val md_theme_light_surfaceVariant = Color(0xFFDBE5E0)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4945)
val md_theme_light_outline = Color(0xFF6F7975)
val md_theme_light_inverseOnSurface = Color(0xFFC3FBFF)
val md_theme_light_inverseSurface = Color(0xFF00373A)
val md_theme_light_inversePrimary = Color(0xFF5DDBBC)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006B58)
val md_theme_light_outlineVariant = Color(0xFFBFC9C4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF5DDBBC)
val md_theme_dark_onPrimary = Color(0xFF00382D)
val md_theme_dark_primaryContainer = Color(0xFF005142)
val md_theme_dark_onPrimaryContainer = Color(0xFF7CF8D8)
val md_theme_dark_secondary = Color(0xFFFFB695)
val md_theme_dark_onSecondary = Color(0xFF571E00)
val md_theme_dark_secondaryContainer = Color(0xFF7A3004)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCC)
val md_theme_dark_tertiary = Color(0xFFFFB86A)
val md_theme_dark_onTertiary = Color(0xFF492900)
val md_theme_dark_tertiaryContainer = Color(0xFF683D00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002022)
val md_theme_dark_onBackground = Color(0xFF70F5FF)
val md_theme_dark_surface = Color(0xFF002022)
val md_theme_dark_onSurface = Color(0xFF70F5FF)
val md_theme_dark_surfaceVariant = Color(0xFF3F4945)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C4)
val md_theme_dark_outline = Color(0xFF89938E)
val md_theme_dark_inverseOnSurface = Color(0xFF002022)
val md_theme_dark_inverseSurface = Color(0xFF70F5FF)
val md_theme_dark_inversePrimary = Color(0xFF006B58)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF5DDBBC)
val md_theme_dark_outlineVariant = Color(0xFF3F4945)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF495E57)
val CustomColor1 = Color(0xFFF4CE14)
val light_CustomColor1 = Color(0xFF705D00)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFE16E)
val light_onCustomColor1Container = Color(0xFF221B00)
val dark_CustomColor1 = Color(0xFFE9C400)
val dark_onCustomColor1 = Color(0xFF3A3000)
val dark_CustomColor1Container = Color(0xFF544600)
val dark_onCustomColor1Container = Color(0xFFFFE16E)
